import {environment} from './environments/environment';

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": environment.awsmobile.aws_cognito_identity_pool_id,
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": environment.awsmobile.aws_user_pools_id,
    "aws_user_pools_web_client_id": environment.awsmobile.aws_user_pools_web_client_id,
    "oauth": {
        "domain": environment.awsmobile.oauth.domain,
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": environment.awsmobile.oauth.redirectSignIn,
        "redirectSignOut": environment.awsmobile.oauth.redirectSignOut,
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
